- hosts: localhost
  vars:
    username: "theprimeagen"
    email: "theprimeagen@gmail.com"
    ssh_key_filename: "id_theprimeagen_rsa"
    config: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    zsh_dependencies: []
  tasks:

  - name: "Install required software"
    become: true
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - git
      - docker
      - docker-compose
      - python3-pip

  - name: Ensure group "docker" exists with correct gid
    become: true
    ansible.builtin.group:
      name: docker
      state: present

  - name: Add user to docker group
    become: true
    ansible.builtin.user:
      name: "{{ username }}"
      groups: docker
      append: true

  - name: Setup keyboard
    become: true
    ansible.builtin.command: ./cmd/keyboard

  - name: user.name for git config
    become_user: "{{ username }}"
    community.general.git_config:
      name: user.name
      scope: global
      value: "{{ username }}"

  - name: user.email for git config
    become_user: "{{ username }}"
    community.general.git_config:
      name: user.email
      scope: global
      value: "{{ email }}"

  # This will copy over all my dev files.
  - include: dev-env.yml
